[package]
name = "tinytools"
version = "0.1.0"
authors = ["Gaoyang Zhang <gy@blurgy.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
